[package]
name = "cream-macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = "1.0"
cream-core = { path = "../core", version = "0.1" }
serde = { version = "1.0" }
serde_json = "1.0"
quote = "1.0"
proc-macro2 = "1.0"
convert_case = "0.6"
